@startuml
start
:Вход в систему;
:Получение заявки руководителем;
if (Есть пересечения отпусков?) then (Да)
  :Отклонить заявку;
else (Нет)
  :Утвердить заявку;
endif
:Уведомление сотруднику;
stop
@enduml