@startuml
start
:Вход в систему;
repeat :Выбор дат отпуска/
if (Соответствует ли заявка\n лимиту отпускных дней?) then (Нет)
  :Ошибка;
else (Да)
  :Сохранить заявку;
  :Отправить руководителю;
  stop
endif
@enduml