@startuml
left to right direction
actor "Сотрудник" as Employee
actor "Руководитель" as Manager
actor "HR" as HR
package "Система Учёта Отпусков" {
  usecase "Подать заявку" as UC1
  usecase "Просмотреть отпускные дни" as UC2
  usecase "Утвердить/Отклонить заявку" as UC3
  usecase "Редактировать данные" as UC4
  usecase "Формировать отчёт" as UC5
}
Employee --> UC1
Employee --> UC2
Manager --> UC3
Manager --> UC2
HR --> UC4
HR --> UC5
@enduml